<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActividadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActividadRepository extends EntityRepository
{

  //Metdodo que retorna las actividades de un encuentro asociado
  public function getActividadesEncuentor($idEncuentro)
  {
    return $this->getEntityManager()
    ->createQuery("SELECT a FROM DataBundle:Actividad a WHERE a.encuentro =:idEncuentro")
    ->setParameter('idEncuentro',$idEncuentro)
    ->getResult();
  }
}
