<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DiplomadoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomadoRepository extends EntityRepository
{
  //Retorna todos los diplomados
  public function findAll()
  {
    return $this->findBy(array(), array('nombre' => 'DESC'));
  }
}
