<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends EntityRepository
{
  //Metodo que lista todos los mentores, tambien es utilizado para cuando
  //Se realizan busquedas
  //@param $querySearch : busqueda a realizar
  public function getAllGrupos($querySearch)
  {
    return $this->getEntityManager()
    ->createQuery("SELECT g FROM DataBundle:Grupo g LEFT JOIN g.jornada gj LEFT JOIN g.diplomado gd LEFT JOIN g.mentor g_m
      LEFT JOIN g_m.mentor m WHERE upper(g.nombre)
    like upper(:querySearch)
     OR upper(gd.nombre) like upper(:querySearch)
     OR upper(gj.nombre) like upper(:querySearch)
     OR upper(m.nombre) like upper(:querySearch)
     OR (CAST(YEAR(g.fechaCreacion) as string) like :querySearch
     OR CAST(MONTH(g.fechaCreacion) as string) like :querySearch
     OR CAST(DAY(g.fechaCreacion) as string) like :querySearch
     OR CONCAT(CONCAT('0',CAST(DAY(g.fechaCreacion) as string)),'-',
      CAST(MONTH(g.fechaCreacion) as string),'-',
      CAST(YEAR(g.fechaCreacion) as string)) like :querySearch)")
    ->setParameter('querySearch','%'.$querySearch.'%');
  }

  //Metodo que retorna todos los grupos que estan activos
  public function getGruposActivos(){
    return $this->getEntityManager()
    ->createQuery("SELECT g FROM DataBundle:Grupo g where g.activo = true")
    ->getResult();
  }


  //Retorna todos los grupos
  public function findAll()
  {
    return $this->findBy(array(), array('id' => 'ASC'));
  }
}
