<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Mentor_GruposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mentor_GruposRepository extends EntityRepository
{
  //Metodo que retorna todos los registros de mentor_grupo teniendo en cuenta
  //el id del mentor
  public function gruposAsignadosPorMentor($idMentor){
    return $this->getEntityManager()
    ->createQuery('SELECT m_g FROM DataBundle:Mentor_Grupos m_g where m_g.mentor = :id
    and m_g.activo = TRUE')
    ->setParameter('id',$idMentor)
    ->getResult();
  }
}
