<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* MentorRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class MentorRepository extends EntityRepository
{
  public function recoverPass($numeroDocumento)
  {
    return $this->getEntityManager()
    ->createQuery("SELECT m.password FROM DataBundle:Mentor mWHERE m.numeroDocumento = :query")
    ->setParameter("query",$numeroDocumento)
    ->getResult();
  }

  //Metodo que lista todos los mentores, tambien es utilizado para cuando
  //Se realizan busquedas
  //@param $querySearch : busqueda a realizar
  public function getAllMentores($querySearch)
  {
    // $em = $this->getEntityManager();
    // $emConfig = $em->getConfiguration();
    // $emConfig->addCustomDatetimeFunction('CAST', 'Oro\ORM\Query\AST\Functions\Cast');
    // $emConfig->addCustomDatetimeFunction('YEAR', 'Oro\ORM\Query\AST\Functions\SimpleFunction');
    // $emConfig->addCustomDatetimeFunction('MONTH', 'Oro\ORM\Query\AST\Functions\SimpleFunction');
    // $emConfig->addCustomDatetimeFunction('DAY', 'Oro\ORM\Query\AST\Functions\SimpleFunction');
    // OR CAST(YEAR(m.fechaNacimiento) as string) like :querySearch)


    return $this->getEntityManager()
    ->createQuery("SELECT m FROM DataBundle:Mentor m JOIN m.tipoMentor tm JOIN m.tipoDocumento td WHERE
      (upper(m.nombre) like upper(:querySearch) OR upper(m.apellidos) like upper(:querySearch)
      OR upper(m.numeroDocumento) like upper(:querySearch) OR upper(m.numeroCelular)
      like upper(:querySearch) OR upper(tm.nombre) like upper(:querySearch)
      OR upper(td.nombre) like upper(:querySearch))")
    ->setParameter('querySearch','%'.$querySearch.'%');
    // ->getResult();
  }

  // //Retorna todos los mentores
  public function findAll()
  {
    return $this->findBy(array(), array('nombre' => 'DESC'));
  }
}
