<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Mentor_GruposRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mentor_GruposRepository extends EntityRepository
{
  //Metodo que retorna todos los registros de mentor_grupo teniendo en cuenta
  //el id del mentor
  public function gruposAsignadosPorMentor($idMentor){
    return $this->getEntityManager()
    ->createQuery('SELECT m_g FROM DataBundle:Mentor_Grupos m_g INNER JOIN m_g.grupo g where m_g.mentor = :id
    and m_g.activo = TRUE and g.activo = TRUE')
    ->setParameter('id',$idMentor)
    ->getResult();
  }

  //Metodo que retorna el id del mentor que esta asignado al grupo que ingresa por parametro
  public function getMentorAsignadoPorGrupo($idGrupo){
    return $this->getEntityManager()
    ->createQuery('SELECT m_g from DataBundle:Mentor_Grupos m_g WHERE m_g.grupo = :id and
    m_g.activo = TRUE')
    ->setParameter('id',$idGrupo)
    ->getOneOrNullResult();
  }

  //Metodo que retorna un detalle asociado con el mentor y grupo asociadoas
  //para obtener la fecha de asignacion y desasigancion
  public function getDetalleMentorGrupo($idMentor,$idGrupo){
    return $this->getEntityManager()
    ->createQuery('SELECT m_g from DataBundle:Mentor_Grupos m_g WHERE m_g.grupo = :idGrupo and
    m_g.mentor =:idMentor and m_g.activo = TRUE')
    ->setParameter('idMentor',$idMentor)
    ->setParameter('idGrupo',$idGrupo)
    ->getOneOrNullResult();
  }

  //Metodo que retorna todo el historial de grupos que han sido asignados a un mentor
  public function getHistoricoGrupos($idMentor){
    return $this->getEntityManager()
    ->createQuery("SELECT m_g from DataBundle:Mentor_Grupos m_g WHERE m_g.mentor =:idMentor")
    ->setParameter('idMentor',$idMentor)
    ->getResult();
  }


}
