<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SemestreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SemestreRepository extends EntityRepository
{

  //Metodo que valida si un semestre ya ha sido creado con su respectivo periodo
  public function validarCreacionSemestre($periodo,$ano){
    return $this->getEntityManager()
    ->createQuery('SELECT s from DataBundle:Semestre s WHERE s.periodo = :periodo and
       CAST(YEAR(s.anoSemestre) as string) like :ano')
       ->setParameter('periodo',$periodo)
       ->setParameter('ano',$ano)
       ->getResult();
  }
}
