<?php

namespace Semillero\DataBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* SemillaRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class SemillaRepository extends EntityRepository
{

  public function recoverPass($numeroDocumento)
  {
    return $this->getEntityManager()
    ->createQuery("SELECT u.password FROM DataBundle:Usuarios u WHERE u.numeroDocumento = :query")
    ->setParameter("query",$numeroDocumento)
    ->getResult();
  }

  //Metodo que lista todos las semillas, tambien es utilizado para cuando
  //Se realizan busquedas
  //@param $querySearch : busqueda a realizar
  public function getAllSemillas($querySearch)
  {
    return $this->getEntityManager()
    ->createQuery("SELECT s FROM DataBundle:Semilla s JOIN s.tipoDocumento td WHERE
      (upper(s.nombre) like upper(:querySearch) OR upper(s.apellidos) like upper(:querySearch)
      OR upper(s.numeroDocumento) like upper(:querySearch) OR upper(s.numeroCelular)
      like upper(:querySearch) OR upper(td.nombre) like upper(:querySearch) OR CAST(YEAR(s.fechaNacimiento) as string) like :querySearch
      OR CAST(MONTH(s.fechaNacimiento) as string) like :querySearch
      OR CAST(DAY(s.fechaNacimiento) as string) like :querySearch
      OR CONCAT(CAST(DAY(s.fechaNacimiento) as string),'-',
      CAST(MONTH(s.fechaNacimiento) as string),'-',
      CAST(YEAR(s.fechaNacimiento) as string)) like :querySearch)")
      ->setParameter('querySearch','%'.$querySearch.'%');
    }

    //Metodo que retorna todas las semillas pertenecientes a un grupo y que esten activos
    public function getSemillasPorGrupo($idGrupo){
      return $this->getEntityManager()
      ->createQuery("SELECT s FROM DataBundle:Semilla s JOIN s.grupos s_g WHERE s_g.grupo = :idGrupo
        and s_g.activo = TRUE")
        ->setParameter('idGrupo',$idGrupo)
        ->getResult();
      }

      // //Retorna todas las semillas
      public function findAll()
      {
        return $this->findBy(array(), array('nombre' => 'DESC'));
      }

    }
