usuarios:
    resource: "@UsuariosBundle/Controller/"
    type:     annotation
    prefix:   /


admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

seguridad:
    resource: "@SeguridadBundle/Controller/"
    type:     annotation
    prefix:   /

data:
    resource: "@DataBundle/Controller/"
    type:     annotation
    prefix:   /

diplomados:
    resource: "@DiplomadosBundle/Controller/"
    type:     annotation
    prefix:   /

mentores:
    resource: "@MentoresBundle/Controller/"
    type:     annotation
    prefix:   /
    options:
        expose: true

semillas:
    resource: "@SemillasBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

semillero_mentores_redirect_edit:
  path: /mentores/update/{numeroDocumento}
  defaults:
    _controller: MentoresBundle:Mentor:edit
    path: /mentores/edit/{numeroDocumento}
    permanent: true
