# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
      # mentor_provider:
      #   entity:
      #     class: DataBundle:Mentor
      #     property: numeroDocumento
      # administrativos_provider:
      #   entity:
      #     class: DataBundle:Administrativo
      #     property: numeroDocumento
      usuarios_provider:
        entity:
          class: DataBundle:Usuarios
          property: numeroDocumento

      admin_provider:
        entity:
          class: DataBundle:Administrador
          property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin_secured_area:
          pattern: ^/admin
          provider: admin_provider
          anonymous: ~

          form_login:
            login_path: /admin/login
            check_path: /admin/login_check
            username_parameter: _username
            password_parameter: _password
          logout:
            path: /admin/logout
            target: /admin/login

        usuarios_secured_area:
          pattern: ^/usuarios
          provider: usuarios_provider
          anonymous: ~

          form_login:
            login_path: /usuarios/login
            check_path: /usuarios/login_check
            username_parameter: _numeroDocumento
            password_parameter: _password
          logout:
            path: /usuarios/logout
            target: /usuarios/login

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    encoders:
     Semillero\DataBundle\Entity\Mentor:
      algorithm: bcrypt
      cost: 12
     Semillero\DataBundle\Entity\Administrador:
      algorithm: bcrypt
      cost: 12
