# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    pagination.service:
      class: Semillero\ServicesBundle\Services\PaginationService
      arguments: []
    service_actividades:
      class: Semillero\ServicesBundle\Controller\ServiceController
      arguments: [@doctrine.orm.entity_manager]
      # arguments: ['@security.context', '@doctrine', '@service_container']
